### PR TITLE
Update Create Percent Access Polygons

### PR DESCRIPTION
**Pull request by d-wasserman**
Update will enable the tool to be imported and use in other scripts while preserving modularity. Main is given a doc string for appropriate Jupyter notebook signatures. Please let me know if an appropriate change, and I can update others accordingly. No functionality should change on the  typical user side, only on the more advanced analyst side.

@mmorang  - Let me know if this type of update is acceptable. I can do additional testing you require.

### CODE REVIEW

**Comment by mmorang** [comment]
Hi David.  Sorry you spent your time on this, as this tool and the other analysis tools have already been revised in a separate branch that will be merged as soon as ArcGIS Pro 2.4 is released (very soon).  I will not be making any further changes to the tools as they stand right now in Master.

See https://github.com/Esri/public-transit-tools/blob/DeprecateAddGTFS/transit-network-analysis-tools/CreatePercentAccessPolygon.py

I suspect the changes in the new branch won't completely satisfy your needs, but we need to work from that branch and not from master.  In that branch, the transit analysis tools have been moved to their own python toolbox (.pyt, not old .tbx).  The input parameters are handled in the .pyt code, and the .pyt calls the main tool script.  I think this is already closer to what you're looking for, and we can add doc strings and stuff as needed.

Can you take a look at that branch and work from there?

**Comment by d-wasserman** [comment]
Hi Melinda, 

I thought I was working from the master, but reviewing the link in question I am not sure that is the case. This is then incompatible. To be clear,  I should work form the DeprecateAddGTFS branch as that will become the new master correct? 

It seems you already made the changes I requested that are core changes. I might then only add doc strings for Jupyter notebooks. Sorry for the confusion, I thought some of this was already merged. 

My bad completely. Thanks for setting me straight. 

David

**Comment by mmorang** [comment]
Looks like you were working from master, but from hence forward, I'm working from the DeprecateAddGTFS branch because that will become the new master very soon.

If you let me know the required format for doc strings for Jupyter notebooks, I'd prefer to write the text myself.  Or just show me an example?  But yeah, let me know if there are other changes necessary.

**Comment by d-wasserman** [comment]
Understood. I tried again from the right branch. You can edit as you like and use it as an example. 

Generally, I got the format I just showed you to work. 
2019-06-17 13_42_26-Access_Elasticity_And_Connectivity_Analysis

**Pull request closed without merging**
