### PR TITLE
Percent Access Polygon Tool

### PR DESCRIPTION
**Pull request by d-wasserman**
Hi Melinda, 

Per our conversation, this is my first attempt at a PR. The tool in this PR will create the following output:

The output polygon from this analysis is a union of each facilities Time Lapse Polygons with fields denoting the percentage of time periods where an area is covered by transit isochrones. The fields of the output feature class will be in the form of:

* FacilityID: This is the same facility ID as the input Time Lapsed Polygons. 
* Name: This is the "FIRST" Name field value encountered as part of a final Dissolve.
* SUMTP{ToBreakNumber}Cnt{Field Number}:  This is the count of the number of time periods with isochrones covering an area. 
* SUMTP{ToBreakNumber}_{Field Number}Perc:  This is the percentage of times time periods with isochrones covering an area. If you want the "50th Percentile" isochrone, you can select all polygons greater than 0.50.

I tested the tool on ArcMap 10.4.1 & ArcGIS Pro 2.1. I will need help testing older versions and getting a screenshot of the tool you would want for the tool. 

Thanks, 

David

### CODE REVIEW

**Comment by mmorang** [comment]
Here is a list of things for me to test (just putting it here for easy tracking).  Feel free to add more specific cases if you have any in mind.

Variants on inputs:
- [ ] Standard single breaks, single facility
- [ ] Multi facility, single break
- [ ] Single facility, multiple breaks, disks
- [ ] Single facility, multiple breaks, rings
- [ ] Multi facility, multiple breaks, disks
- [ ] Multi facility, multiple breaks, rings
- [ ] Huge number of input facilities
- [ ] Huge number of breaks

License and version checks
- [ ] Works on 10.1/10.2 (backwards compatibility)
- [ ] Works in Pro (strictly speaking, doesn't actually need to)
- [ ] Works with basic license, or has appropriate license check
- [ ] Works without NA or other extension licenses, or has appropriate license check

**Comment by Holisticnature** [comment]
The only thing I might add that I am not sure I do right now. 
Special Case Checks
- [ ] Shapefile output possible. 

Not sure if this is a good requirement to add in, but I can make changes to check that it does...I think field name lengths would be the issue here.

**Comment by mmorang** [comment]
Oh yeah, definitely.  Stupid me for forgetting.  Shapefile input and output has to either work or be explicitly forbidden.  I'm okay with either.

**Comment by mmorang** [comment]
So...Spatial Join runs out of memory for what I consider a quite reasonable-sized test case (one facility, 20-minute break, 60 time steps over an hour).  I'll e-mail you the data.

**Comment by Holisticnature** [comment]
Lets try using this version for now. I have shapefile support to up to 100 breaks I believe. As we discussed supporting multiple breaks is difficult, but this tool gets close. I think this can be useful to most users for release now. Per our conversations this current version:

- Scales to a large number of time periods

- Speed is adjustable based on cell size, and generally run time is better or comparable to our previous ideas related to unions vs. cell statistics. 

- This version supports 10.2+ and addresses a bug in 10.6

- This version should support a large number of breaks, but maybe more testing is needed

- This version has a percentage threshold as a shortcut function for users to get an arbitrary percentile isochrone

- Does not require a SA license, but it might require advanced

**Comment by Holisticnature** [comment]
Hi Melinda, 

Per our email conversation, this version makes a series of changes to address bugs and provide a little more consistency with a design doc you and I have been discussing over email.
Next steps are as I see them: 

- [ ] Finalize Design Doc at UC

- [ ] Incorporate Changes

- [ ] Test Tool

- [ ] Final PR and Merge

**Comment by mmorang** [comment]
Just wanted to let you know that I'm working on this, and it's coming along.
image
^ How cool does that look?

**Comment by mmorang** [comment]
Superseded by https://github.com/Esri/public-transit-tools/pull/127

**Pull request closed without merging**
