### PR TITLE
Add Doc String - Percent Access Polygons

### PR DESCRIPTION
**Pull request by d-wasserman**
Hi Melinda, 

This is just then a cosmetic change relative to before. I see in our past conversation, I just started in the wrong location. Thanks for taking care of this across functions. 

You can decide not take this in the near future. I can add doc-strings to other main functions if you would like someone to take a shot at it. 

Thanks, 

David

### CODE REVIEW

**Comment by d-wasserman** [comment]
Sample Signature. Details to update as you please. This is a low priority change. 
2019-06-17 13_42_26-Access_Elasticity_And_Connectivity_Analysis

**Comment by mmorang** [comment]
I guess this is the "Sphinx" style?

**Comment by mmorang** [comment]
The reason I ask about style is because I'm more accustomed to seeing them like this:
image

**Comment by d-wasserman** [comment]
I guess so. There are multiple styles for doc strings, and they all vary in acceptability. 

We can adjust the tools to match that style. I think your doc-string is better. It is a minor thing.

**Comment by mmorang** [comment]
I just pushed the change in my screenshot above to this branch (DeprecateAddGTFS). Can you see if it works for what you're doing or if I need to adjust the formatting?

**Comment by d-wasserman** [comment]
This works. Thanks!
image

**Comment by mmorang** [comment]
Magic!  Okay, I'll do the other tools using the same text as is in the users guides, and we'll call it good.

**Comment by d-wasserman** [comment]
Understood. Thanks Melinda!

**Comment by mmorang** [comment]
I added doc strings to all four tools that are going over to the new Transit Network Analysis Tools toolbox.  Create Percent Access Polygons is the only one that has a main() function.  The others use a generic runTool() function.  If you need the others to have main(), let me know.

**Pull request closed without merging**
