### PR TITLE
Add job accessibility tool

### PR DESCRIPTION
**Pull request by mmorang**
Adding the Calculate Accessibility Matrix tool to the Transit Analysis Tools toolbox in the Add GTFS to a Network Dataset suite.

We often want to analyze "accessibility" in a city, how much access people or places have to certain types of facilities or opportunities. For example, we might want to know how many jobs people in different neighborhoods of a city have access to within a reasonable commute time. The Calculate Accessibility Matrix tool can help you calculate some measures of accessibility. Given a set of origins and destinations, this tool counts the number and percentage of destinations reachable from each origin by transit and walking within a travel time limit. The number of reachable destinations can be weighted based on a field, such as the number of jobs available at each destination.

The results of analyses performed using your GTFS-enabled network dataset can vary greatly depending upon the time of day used as the start time for your analysis. An analysis run at 8:00 AM might have a very different solution than one run at 8:01 AM. A given origin might have access to a given destination at 8:00 AM but not at 8:01 AM if, by starting at 8:01 AM, the traveler has just missed the bus.

The Calculate Accessibility Matrix tool attempts to account for the dynamic nature of transit schedules by solving an Origin-Destination Cost Matrix analysis for multiple times of day and summarizing the results. The user specifies a time window, and the tool will run the analysis for each minute within the time window. In addition to counting the total number of destinations reachable at least once during the time window, the tool output also shows the number of destinations reachable at least 10%, 20%, ...90% of start times during the time window.

### CODE REVIEW

**Comment by mmorang** [comment]
@Holisticnature I would be interested in your feedback on what I just added.  I haven't incorporated it into the downloadable ArcGIS Online version yet because I'm hoping to be able to add another major upgrade into the package soon, but the new stuff is here on GitHub.

This new tool isn't going to be that great for a super-serious analyst who wants to solve a massive problem, but it's meant to be usable for someone doing some exploratory calculations of, say, job accessibility in a single metro area.

**Comment by Holisticnature** [comment]
This is something I was thinking about doing if you did not! =) Seeing your progress on this front is a huge plus. We typically would have to think about building something ourselves for something like this.  I could see us using this tool in an upcoming project (but we are working on incorporating historical AVL into the analysis as well so- plot twist). 

I think one of the issues I have had with pursuing this is the best accessibility analysis would try to deal with the [temporal variation with transit start times](https://blog.conveyal.com/representing-service-variation-in-accessibility-measures-af727b317a36) in a robust but efficient way. You mention you deal with multiple times of day, but I am curious how you select the distribution of times to select. Do you just build a percentile distribution? Can a user select the time increment? I think parameters to limit processing are ideal. I will have to review the code in detail though to give a firm answer.

**Comment by mmorang** [comment]
The user selects a time window and a time increment, which defaults to 1 minute.  So, you could pick 8:00-8:59 with an increment of 1, and it would run the OD 60 times.  Or you could set the increment to 2, and it would calculate it only 30 times, skipping every other minute.

I mean, this solution works, but it's definitely not very efficient.  From what I understand, there are algorithmic/graph search ways to solve a problem like this all in one go that would be drastically more efficient, but implementing something like that in the current Network Analyst environment would require writing a custom solver in ArcObjects, which isn't something I'm at all prepared to do.  If someone has a spare algorithms developer lying around with nothing to do, though...

**Comment by Holisticnature** [comment]
I was thinking about something a little simpler. Allow 1 minute increments fine, but perhaps a parameter that allows random sampling. For example, I might want a 24 hour accessibility shed but don't want to deal with potential increment bias from picking a half hour time increments.  I likely just need to allow a random sampling of time points to sample (200 1 minute increments across the day). 

For example: Time window 8 AM to 6 PM- Sample Increment 1 Minute - Default Sample points is all time points (use validator to set I guess), but that optional parameter can be adjusted so that the number of sample points can be reduced to 100. My concern is that the increment can in and of itself bias the results (just based on how some stop times are scheduled, especially for synthetic GTFS datasets used in service planning). Does it add another parameter? Yes. Is it worth it? I think so (especially if it can have smart defaults). 
My new favorite function for this purpose is :https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html
A smart way to use this function would be to use the weighting function to simulate actual user behavior (IE weight the based on a custom table provided by the user- for example I can look at ridership data and weight my sample points based on the ridership by hour). For example, arrival times for a suburban low frequency route is likely very different from that of a 10 minute headways N line in Manhattan (IE the suburban user is more schedule aware).

**Comment by mmorang** [comment]
Oh, I see what you're talking about.  Interesting idea.  I will give it some thought after I get through this all-day pre-conference workshop I'm giving at GIS in Transit.  The tool as it is now was the bare minimum I needed to get through that.  :)

**Comment by Holisticnature** [comment]
I would be happy to help add this feature to this tool if you trust you can delegate it to me. Either way, I just think a feature like this allows robust analysis that scale with the computing power available to a user. It also might be helpful for testing an analysis workflow before finalizing it (IE decreasing sampling to 15 points for testing purposes in  a larger workflow but then increase it to 500 for a final result).

**Pull request merged**
